[General]
max_normalised_diff_percent = 1

; Collectors to exclude from the diff calculation
[ExcludeFromDiff]
IPRoutesCollector
ScyllaSSTablesCollector
IPAddressesCollector

; Analyzers that need to be skipped
;[SkipTest]
;CPUScalingAnalyzer

;[ScyllaExtraConfigurationFilesCollector]
;mask=[('files','memory.conf'), ('files','housekeeping.cfg'), ('files','io.conf', 'SEASTAR_IO')]