# IMPORTANT:
# This file allows you to configure Scylla Doctor's behavior.

#---<[ GENERAL ]>---
; [DefaultPaths]
; scylla_directory = /opt/scylladb
; scylla_directory_config = /etc/scylla
; scylla_directory_configs = /etc/scylla.d
; scylla_directory_var = /var/lib/scylla

; [CQL]
# If authentication is enabled, user and password values will be used for such process
; user = cassandra
; password = cassandra
# If Scylla is listening for CQL on an address and port different from specified in scylla.yaml, set them here:
; rpc_address = <address>
; native_transport_port = <port>
; use_ssl = [no|yes]

#---<[ COLLECTORS ]>---
# An example:
# [CPUSpecificationsCollector]
# run = yes

#---<[ ANALYZERS ]>---
# An example:
# [CPUInstructionSetAnalyzer]
# run = yes

; [ScyllaSSTablesAnalyzer]
; recommended_format = md

; [ScyllaSupportAnalyzer]
; oss_minimum_version = 5.0
; enterprise_minimum_version = 2022.1

# [ScyllaInternodeCompressionAnalyzer]
# recommended_compression = all

#[DriverVersionAnalyzer]
#minimum_version = {
#        "Java" : "3.14.0",
#        "Go": "3.45",
#        "Python": "4"
#        "CPP": "2.15.2",
#        "Rust": "0.5",
#    }
#latest_version = {
#        "Java" : "4.17.0",
#        "Go": "3.45",
#        "Python": "4"
#        "CPP": "2.15.2",
#        "Rust": "0.5",
#    }}
